# Generated by Django 5.2.8 on 2025-11-21 21:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_discount_tax_item_currency_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={
                "ordering": ["percent"],
                "verbose_name": "Скидка",
                "verbose_name_plural": "Скидки",
            },
        ),
        migrations.AlterModelOptions(
            name="tax",
            options={
                "ordering": ["percent"],
                "verbose_name": "Налог",
                "verbose_name_plural": "Налоги",
            },
        ),
        migrations.RemoveField(
            model_name="discount",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tax",
            name="name",
        ),
    ]
